name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake_dir
      run: mkdir cmake_dir && cd cmake_dir
    - name: cmake
      run: cmake ..
    - name: make
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: Single Linked List Static Library
        path: cmake_dir/singlelinkedlists.a
    - uses: actions/upload-artifact@v2
      with:
        name: Doubly Linked List Static Library
        path: cmake_dir/doublylinkedlists.a
