name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: Single Linked List Static Library
        path: build_libs/singlelinkedlists.a
    - uses: actions/upload-artifact@v2
      with:
        name: Doubly Linked List Static Library
        path: build_libs/doublylinkedlists.a
